import MetamaskIcon from '../assets/metamask.svg';
import Coinbase from '../assets/coinBaseLogo.svg';
import WalletIcon from '../assets/WalletConnect.svg';
import { useWalletAuth } from '../hooks/useWalletAuth';
import { Box, Typography, Button, Divider } from '../shared/kit';
import Image from 'next/image';
import Head from 'next/head';
import Login from '../widgets/authFirebase';


const wallets = [
  {
    id: 'meta',
    title: 'Metamask',
    img: MetamaskIcon,
  },
  {
    id: 'coin',
    title: 'Coinbase',
    img: Coinbase,
  },
  {
    id: 'wal',
    title: 'Wallet Conect',
    img: WalletIcon,
  },
];
export default function Home() {
  const { handleAuth } = useWalletAuth();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="section">
        <Box
          style={{
            width: '100%',
            flexDirection: 'column',
            justifyContent: 'center',
            gap: 10,
            borderRadius: '8px',
          }}
        >
          <Typography variant="h4" sx={{ py: 5, textAlign: 'center' }}>
            Connect your wallet
          </Typography>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: '15px', alignItems: 'center' }}>
            {wallets.map((wallet) => (
              <Box key={wallet.id}>
                <Button
                  onClick={() => handleAuth(wallet.id)}
                  variant="contained"
                  startIcon={<Image src={wallet.img} alt={wallet.id} width={25} />}
                  sx={{ width: '300px', borderRadius: '25px', height: '40px' }}
                >
                  {wallet.title}
                </Button>
              </Box>
            ))}
            <Login />
          </Box>
        </Box>
      </div>
    </>
  );
}
